parent_config: './conf/qa/squad/abstract_squad.yaml'
seed: 1337

repr_dim: 256
dropout: 0.2
learning_rate: 0.0005
with_wiq: False
num_interactive: 0

reader: 'non_interactive_qa_reader'
name: 'noninteractive_bilstm'

encoder:
  - input: 'text'
    module: 'lstm'
    with_projection: True
    residual: True
    num_layers: 1
