parent_config: './conf/qa/squad/abstract_squad.yaml'
seed: 1337

repr_dim: 256
dropout: 0.2
learning_rate: 0.0005
learning_rate_decay: 0.8
with_wiq: False
num_interactive: 0
epochs: 12

reader: 'non_interactive_qa_reader'
name: 'noninteractive_bilstm'

encoder:
  - input: 'text'
    output: 'output_0'
    module: 'lstm'
    num_layers: 1
    with_projection: True
    residual: True


gated_bow: {num_slots: 1}
