parent_config: './conf/qa/squad/abstract_squad.yaml'
seed: 1337

repr_dim: 128
dropout: 0.2
epochs: 15
learning_rate: 0.0005

reader: 'hierarchical_segments_qa_reader'
name: 'hierarchical_segments_qa_reader'

depth: 2
