parent_config: './conf/qa/squad/abstract_squad.yaml'
seed: 1337

repr_dim: 256
dropout: 0.2
learning_rate: 0.0005

reader: 'interactive_hierarchical_segments_qa_reader'
name: 'interactive_hierarchical_segments_qa_reader'

num_layers: 2
