parent_config: './conf/qa/squad/abstract_squad.yaml'
seed: 1337

repr_dim: 256
dropout: 0.2
learning_rate: 0.0005
learning_rate_decay: 0.8
with_wiq: False
num_interactive: 0
epochs: 15
is_interactive: False

reader: 'non_interactive_qa_reader'
name: 'noninteractive_qanet'


encoder_block: &encoder_block
  - input: 'text'
    module: 'conv_separable'
    conv_width: 7
    num_layers: 4
    residual: True
    layer_norm: True

  - input: 'text'
    output: 'text_self'
    module: 'self_attn'
    attn_type: 'dot'
    scaled: True
    num_attn_heads: 8
    key_value_attn: True
    repr_dim: 32
    layer_norm: True

  - input: 'text_self'
    module: 'dense'
    activation: 'relu'

  - input: ['text', 'text_self']
    output: 'text'
    module: 'add'


encoder: &encoder
  #- input: 'text'
  #  module: 'positional_encoding'

  - module: 'repeat'
    num: 1
    reuse: False
    encoder: *encoder_block

  - input: 'text'
    output: 'output_1'
    module: 'dense'
    activation: 'relu'
    layer_norm: True


post_non_interactive:
  encoder:
    - input: 'support'
      dependent: 'question'
      output: 'support_attn'
      module: 'coattention'
      attn_type: 'diagonal_bilinear'
      concat: False

    - input: ['support', 'support']
      output: 'support_x2'
      module: 'concat'

    - input: ['support_x2', 'support_attn']
      output: 'support_attn_mul'
      module: 'mul'

    - input: ['support', 'support_attn', 'support_attn_mul']
      output: 'support'
      module: 'concat'

    - input: 'support'
      output: 'text'
      module: 'dense'
      activation: 'tanh'

    - *encoder

  answer_layer:
    support: 'text'
    question: 'question'
    module: 'bilinear'
