description: >
  assertion generation configuration

parent_config: './conf/jack.yaml'


assertion_dir: '/data/assertion_shelve'
assertion_limit: 20
assertion_sources: ['conceptnet']

seed: 1337

reader: 'predicate_generator_fixed'

reader_dir: './predicate_generator_fixed'

loader: assertion

vocab_from_embeddings: True
with_char_embeddings: True

repr_dim: 300
epochs: 20
batch_size: 128

num_negatives: 1
max_concept_vocab: 100000
